# https://pre-commit.com/
#
# Before first use: `pre-commit install`
# To run: `pre-commit run --all-files`
# To update: `pre-commit autoupdate`
#  - &flake8_dependencies below needs updated manually
fail_fast: true
default_language_version:
    python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      # - id: trailing-whitespace
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.20.2
    hooks:
      - id: validate-pyproject
        name: Validate pyproject.toml
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--in-place]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  # - repo: https://github.com/MarcoGorelli/auto-walrus
  #   rev: v0.2.2
  #   hooks:
  #     - id: auto-walrus
  #       args: [--line-length, "100"]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
      # - id: black-jupyter
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: &flake8_dependencies
        # These versions need updated manually
        - flake8==7.1.1
        - flake8-comprehensions==3.15.0
        - flake8-bugbear==24.8.19
        # - flake8-simplify==0.20.0
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies: *flake8_dependencies
  # `pyroma` may help keep our package standards up to date if best practices change.
  # This is a "low value" check though and too slow to run as part of pre-commit.
  # - repo: https://github.com/regebro/pyroma
  #   rev: "4.2"
  #   hooks:
  #     - id: pyroma
  #       args: [-n, "10", .]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch  # no commit directly to main
