# https://pre-commit.com/
#
# Before first use: `pre-commit install`
# To run: `pre-commit run --all-files`
# To update: `pre-commit autoupdate`
#  - &flake8_dependencies below needs updated manually
fail_fast: true
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: forbid-submodules
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: name-tests-test
        args: ["--pytest-test-first"]
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
        name: Validate pyproject.toml
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.3
    hooks:
      - id: autoflake
        args: [--in-place]
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
        additional_dependencies: &flake8_dependencies
        # These versions need updated manually
        - flake8==7.3.0
        - flake8-comprehensions==3.17.0
        - flake8-bugbear==25.11.29
        # - flake8-simplify==0.22.0
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies: *flake8_dependencies
  # `pyroma` may help keep our package standards up to date if best practices change.
  # This is a "low value" check though and too slow to run as part of pre-commit.
  # - repo: https://github.com/regebro/pyroma
  #   rev: "5.0.1"
  #   hooks:
  #     - id: pyroma
  #       args: [-n, "10", .]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.11.0.1"
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-no-log-warn
      - id: text-unicode-replacement-char
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.0
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch  # no commit directly to main
