name: suitesparse-graphblas
channels:
  - conda-forge
  - nodefaults  # Only install packages from conda-forge for faster solving
dependencies:
  # - graphblas=6.0.2
  - cffi
  - cython
  - numpy
  - pytest
  - pytest-randomly
  - coverage
  - pycparser
