name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10"]
        # source: ["conda-forge"]
        source: ["source"]
        graphblas-version: ["7.0.1"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        environment-file: continuous_integration/environment.yml
        channels: conda-forge
        activate-environment: suitesparse-graphblas
    - name: GraphBLAS (from conda-forge)
      if: (contains(matrix.source, 'conda-forge'))
      run: |
        conda install -c conda-forge graphblas=${{ matrix.graphblas-version }}
    - name: GraphBLAS (from source)
      if: (contains(matrix.source, 'source'))
      run: |
        # This isn't working!  Why not?
        # sh suitesparse.sh refs/tags/${{ matrix.graphblas-version }}
        curl -L https://github.com/DrTimothyAldenDavis/GraphBLAS/archive/refs/tags/v${{ matrix.graphblas-version }}.tar.gz | tar xzf -
        pushd GraphBLAS-${{ matrix.graphblas-version }}/build
        echo ${CONDA_PREFIX}
        cmake -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release ..
        cat Makefile
        make all JOBS=16
        make install
        popd
    - name: Build
      run: |
        python setup.py build_ext --inplace
        python setup.py develop
    - name: Test
      env:
        CYTHON_COVERAGE: true
      run: |
        coverage run --branch -m pytest
        coverage run -a --branch suitesparse_graphblas/tests/test_initialize.py
    - name: Lint
      run: |
        black *py suitesparse_graphblas --check --diff
        flake8 *py suitesparse_graphblas
    - name: create_headers.py check
      if: (! contains(matrix.os, 'windows'))
      run: |
        coverage run -a --branch suitesparse_graphblas/create_headers.py
        git diff --exit-code  # error if anything changed
