name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        os: ["ubuntu-latest"]
        # python-version: [3.7, 3.8, 3.9]
        python-version: [3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        environment-file: continuous_integration/environment.yml
        channels: conda-forge
        activate-environment: suitesparse-graphblas
    - name: Build
      run: |
        # sh suitesparse.sh refs/tags/6.0.0.alpha11
        curl -L https://github.com/DrTimothyAldenDavis/GraphBLAS/archive/refs/tags/v6.0.0.alpha11.tar.gz | tar xzf -
        pushd GraphBLAS-6.0.0.alpha11/build

        export PREFIX="${CONDA_PREFIX}"
        export INSTALL="${PREFIX}"
        export CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release"
        echo ${CMAKE_OPTIONS}

        cmake ..
        make VERBOSE=1 JOBS=16
        make install VERBOSE=1
        popd

        python setup.py build_ext --inplace
        python setup.py develop
    - name: Test
      env:
        CYTHON_COVERAGE: true
      run: |
        coverage run --branch -m pytest
        coverage run -a --branch suitesparse_graphblas/tests/test_initialize.py
    - name: Lint
      run: |
        black *py suitesparse_graphblas --check --diff
        flake8 *py suitesparse_graphblas
    - name: create_headers.py check
      if: (! contains(matrix.os, 'windows'))
      run: |
        # These shouldn't change, so make copies to compare to
        cp suitesparse_graphblas/suitesparse_graphblas.h .
        cp suitesparse_graphblas/suitesparse_graphblas_no_complex.h .
        cp suitesparse_graphblas/source.c .
        coverage run -a --branch suitesparse_graphblas/create_headers.py
        diff suitesparse_graphblas/suitesparse_graphblas.h suitesparse_graphblas.h
        diff suitesparse_graphblas/suitesparse_graphblas_no_complex.h suitesparse_graphblas_no_complex.h
        diff suitesparse_graphblas/source.c source.c
