name: python-suitesparse-graphblas

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7, 3.8, 3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: Build
      run: |
        conda info
        conda list
        conda install -c conda-forge cffi cython numpy graphblas pytest coverage black flake8  # TODO: environment.yml
        python setup.py build_ext --inplace
        python setup.py develop
    - name: Test
      env:
        CYTHON_COVERAGE: true
      run: |
        coverage run --branch -m pytest
    - name: Lint
      run: |
        black *py suitesparse_graphblas --check --diff
        flake8 *py suitesparse_graphblas
